RaktarInformatika0430/Models/Aru.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RaktarInformatika0430.Models
{
    public class Aru
    {
        public int Id { get; set; }

        [Display(Name="Megnevezés")]
        [StringLength(60)]
        public string Megnevezes { get; set; }
        
        [Display(Name="Beszállító")]
        [StringLength(30)]
        public string Beszallito { get; set; }

        [Display(Name ="Beszerzési Ár")]
        [Column(TypeName="decimal(10,2)")]
        public decimal Ar { get; set; }
    }
}

RaktarInformatika0430/Models/AruKeres.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RaktarInformatika0430.Models
{
    public class AruKeres
    {
        public string Megnevezes { get; set; }
        public string Beszallito { get; set; }
        public List<Aru> AruLista { get; set; }
        public SelectList BeszallitoLista { get; set; }
    }
}

RaktarInformatika0430/Models/ErrorViewModel.cs
using System;

namespace RaktarInformatika0430.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RaktarInformatika0430/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RaktarInformatika0430.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RaktarInformatika0430.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RaktarInformatika0430/Controllers/RaktarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RaktarInformatika0430.Data;
using RaktarInformatika0430.Models;

namespace RaktarInformatika0430.Controllers
{
    public class RaktarController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RaktarController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Raktar
        public async Task<IActionResult> Index(string Megnevezes, string Beszallito)
        {
            var model = new AruKeres();
            var aruk = _context.Aru.Select(x=>x);
            if (!string.IsNullOrEmpty(Megnevezes))
            {
                aruk = aruk.Where(x => x.Megnevezes.Contains(Megnevezes));
                model.Megnevezes = Megnevezes;
            }
             if (!string.IsNullOrEmpty(Beszallito))
            {
                aruk = aruk.Where(x => x.Beszallito==Beszallito);
                model.Beszallito=Beszallito;
            }

            model.AruLista = await aruk.OrderBy(x => x.Megnevezes).ToListAsync();
            model.BeszallitoLista = new SelectList(await _context.Aru.Select(x=>x.Beszallito).Distinct().OrderBy(x=>x).ToListAsync());

            return View(model);
        }

        // GET: Raktar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aru = await _context.Aru
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aru == null)
            {
                return NotFound();
            }

            return View(aru);
        }

        // GET: Raktar/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Raktar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Megnevezes,Beszallito,Ar")] Aru aru)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aru);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aru);
        }

        // GET: Raktar/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aru = await _context.Aru.FindAsync(id);
            if (aru == null)
            {
                return NotFound();
            }
            return View(aru);
        }

        // POST: Raktar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Megnevezes,Beszallito,Ar")] Aru aru)
        {
            if (id != aru.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aru);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AruExists(aru.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aru);
        }

        // GET: Raktar/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aru = await _context.Aru
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aru == null)
            {
                return NotFound();
            }

            return View(aru);
        }

        // POST: Raktar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aru = await _context.Aru.FindAsync(id);
            _context.Aru.Remove(aru);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AruExists(int id)
        {
            return _context.Aru.Any(e => e.Id == id);
        }
    }
}

RaktarInformatika0430/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RaktarInformatika0430/Views/Raktar/Create.cshtml
@model RaktarInformatika0430.Models.Aru

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aru</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Megnevezes" class="control-label"></label>
                <input asp-for="Megnevezes" class="form-control" />
                <span asp-validation-for="Megnevezes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beszallito" class="control-label"></label>
                <input asp-for="Beszallito" class="form-control" />
                <span asp-validation-for="Beszallito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ar" class="control-label"></label>
                <input asp-for="Ar" class="form-control" />
                <span asp-validation-for="Ar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RaktarInformatika0430/Views/Raktar/Delete.cshtml
@model RaktarInformatika0430.Models.Aru

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aru</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Megnevezes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Megnevezes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beszallito)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beszallito)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ar)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RaktarInformatika0430/Views/Raktar/Details.cshtml
@model RaktarInformatika0430.Models.Aru

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Aru</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Megnevezes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Megnevezes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beszallito)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beszallito)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ar)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RaktarInformatika0430/Views/Raktar/Edit.cshtml
@model RaktarInformatika0430.Models.Aru

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Aru</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Megnevezes" class="control-label"></label>
                <input asp-for="Megnevezes" class="form-control" />
                <span asp-validation-for="Megnevezes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beszallito" class="control-label"></label>
                <input asp-for="Beszallito" class="form-control" />
                <span asp-validation-for="Beszallito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ar" class="control-label"></label>
                <input asp-for="Ar" class="form-control" />
                <span asp-validation-for="Ar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RaktarInformatika0430/Views/Raktar/Index.cshtml
@model RaktarInformatika0430.Models.AruKeres

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Raktar" asp-action="Index" method="get">
Megnevezés:
<input asp-for="Megnevezes">

Beszállító:
<select asp-for="Beszallito" asp-items="Model.BeszallitoLista">
<option value="">Összes</option>
</select>
<input type="submit" value="Keresés">
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AruLista[0].Megnevezes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AruLista[0].Beszallito)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AruLista[0].Ar)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.AruLista) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Megnevezes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Beszallito)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ar)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RaktarInformatika0430/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RaktarInformatika0430</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RaktarInformatika0430</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Jáger Attila - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>